# Generated by Django 5.2.3 on 2025-11-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_comments_posted_at_listings_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("art", "Art & Antiques"),
                    ("jewelry", "Jewelry"),
                    ("collectibles", "Collectibles"),
                    ("luxury", "Luxury Goods"),
                ],
                default="art",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="listings",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_images/"),
        ),
        migrations.AlterField(
            model_name="listings",
            name="bid_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listings",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
